import React from 'react'
import './termsandconditions.css'
const TermsandConditions = () => {
  return (
    <div className="terms-conditions-container">
      <h1 className='terms-conditions-title'>Terms & Conditions</h1>

      <h2>Introduction</h2>
      <p>
        This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>
      <p>
        This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011, which requires publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name <b>https://masterpramod.com/</b> (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”).
      </p>
      <p>
        The Platform is owned by <b>Live Healthy and Be Safe</b>, a company incorporated under the Companies Act, 1956, with its registered office at 267, Goyal Nagar, Near Bangali Square, Indore, MP 452018 (hereinafter referred to as “Platform Owner”, “we”, “us”, “our”).
      </p>

      <h2>Acceptance of Terms</h2>
      <p>
        By accessing, browsing, or otherwise using the Platform, you agree to be bound by all the terms and conditions under these Terms of Use. Please read these Terms of Use carefully before proceeding. If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such transactions. By mere use of the Platform, you shall be contracting with the Platform Owner, and these terms and conditions, including the policies, constitute your binding obligations with the Platform Owner.
      </p>
      <p>
        These Terms of Use relate to your use of our website, goods (as applicable), or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
      </p>
      <p>
        For the purpose of these Terms of Use, wherever the context so requires, “you”, “your” or “user” shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
      </p>

      <h2>General Terms of Use</h2>
      <ol>
        <li>
          <b>Account Information:</b> To access and use the Services, you agree to provide true, accurate, and complete information during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
        </li>
        <li>
          <b>No Warranty:</b> Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services, for any specific purpose. Such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
        </li>
        <li>
          <b>Use at Your Own Risk:</b> Your use of our Services and the Platform is solely and entirely at your own risk and discretion. You are required to independently assess and ensure that the Services meet your requirements. We shall not be liable to you in any manner.
        </li>
        <li>
          <b>Intellectual Property:</b> The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents, including but not limited to the design, layout, look, and graphics.
        </li>
        <li>
          <b>Unauthorized Use:</b> Unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.
        </li>
        <li>
          <b>Payment:</b> You agree to pay us the charges associated with availing the Services.
        </li>
        <li>
          <b>Lawful Use:</b> You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, or Indian or local laws that might apply to you.
        </li>
        <li>
          <b>Third-Party Links:</b> The Platform and the Services may contain links to other third-party websites. On accessing these links, you will be governed by the terms of use, privacy policy, and such other policies of such third-party websites. These links are provided for your convenience to provide further information.
        </li>
        <li>
          <b>Binding Contract:</b> Upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
        </li>
        <li>
          <b>Indemnity:</b> You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (as applicable), and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys’ fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use, Privacy Policy, and other policies, or your violation of any law, rules or regulations, or the rights (including infringement of intellectual property rights) of a third party.
        </li>
        <li>
          <b>Limitation of Liability:</b> In no event will the Platform Owner be liable for any indirect, consequential, incidental, special, or punitive damages, including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data, or loss of other economic interests, whether in contract, negligence, tort, or otherwise, arising from the use of or inability to use the Services. Our liability shall not exceed the amount paid by you for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100), whichever is less.
        </li>
        <li>
          <b>Force Majeure:</b> Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
        </li>
        <li>
          <b>Governing Law:</b> These Terms and any dispute or claim relating to them, or their enforceability, shall be governed by and construed in accordance with the laws of India.
        </li>
        <li>
          <b>Jurisdiction:</b> All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in 267, Goyal Nagar, Near Bangali Square, Indore, MP 452018.
        </li>
        <li>
          <b>Contact:</b> All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
        </li>
      </ol>

      <h2>Information Collection & Usage</h2>
      <p>
        When you access or use our Site, we collect information about how you have used our Site and our services. Certain information is stored in our servers automatically, including but not limited to: data about the pages you access within the Site, user choices and behavior, your IP address, device identity or unique identifier, device type, geo-location information (on obtaining consent), device and connection information, mobile network information, statistics on page views, traffic to and from the sites, referral URL, ad data, and standard web log data. We also collect anonymous information through our use of cookies and web beacons.
      </p>
      <p>
        We may collect and store any information you provide us when you use our services, including when you:
      </p>
      <ul>
        <li>Add information on a web form</li>
        <li>Add, edit, or update your Account information</li>
        <li>Contact us for support or other offerings</li>
        <li>Participate in community discussions, chats, etc.</li>
        <li>Send any messages to us or correspond with us regarding the Site or our services</li>
        <li>Respond to a survey conducted by us</li>
        <li>Register for a promotion provided by us</li>
        <li>Request certain features (e.g., newsletters, updates, etc.)</li>
        <li>Submit feedback to us</li>
        <li>Create, upload, or post content on the Site</li>
      </ul>

      <h2>Cookies and Tracking Technologies</h2>
      <p>
        The Site uses persistent and session cookies and other similar technologies to offer you a personalized experience and to remember your browsing preferences, including your login details and choice of language. Cookies are stored primarily to ensure that in the event you return to the Site, it shall personalize your browsing, including enabling you to be logged on the Site automatically. This information may, where permitted by applicable law, also be combined with other information we hold about you.
      </p>
      <p>
        The cookies are uniquely assigned to you and can only be accessed by your web page server in our domain. You can disable our cookies or all cookies through your browser settings. Upon the beginning of each of your visits to the Site, the Site also provides the choice to turn off all cookies which are not strictly necessary for the provision of our services. Please be advised that disabling cookies through either method may impact many of the Site’s features. In addition to cookies, we and/or our third-party advertising partners may use technologies that help us better manage and analyze content.
      </p>

      <h2>Buttons, Tools & Content from Other Companies</h2>
      <p>
        The Site may include buttons, tools, or content that link to other companies’ services, such as Facebook, Twitter, Instagram, and LinkedIn. We may collect information about your use of these features. In addition, when you see or interact with these buttons, tools, or content, or view a web page on the Site, some information from your browser may automatically be sent to the other company, in accordance with the terms and conditions of such other company.
      </p>

      <h2>Contacting the Company</h2>
      <p>
        We may also collect information about you from other sources, such as through your contact with us, including our customer support and/or social media team, and your interactions with other users. Additionally, for quality and training purposes or for our own protection, we may monitor or record telephone conversations with you or anyone acting on your behalf. By communicating with us, you acknowledge that your communication may be overheard, monitored, or recorded without further notice or warning.
      </p>
    </div>
  )
}

export default TermsandConditions